server:
  port: 9000
spring:
  datasource:
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      # 5分钟
      idle-timeout: 300000
      pool-name: api-pool
      connection-timeout: 30000
    username: root
    password: 123456
    url:  jdbc:mysql://localhost:3306/szzj?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
pagehelper:
  row-bounds-with-count: true
  offset-as-page-num: true
  reasonable: true